"""empty message

Revision ID: 3e192218884d
Revises: 
Create Date: 2017-04-21 02:49:39.435596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e192218884d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=60), nullable=True),
    sa.Column('player_yob', sa.String(length=60), nullable=True),
    sa.Column('grade_1', sa.String(length=60), nullable=True),
    sa.Column('grade_a', sa.String(length=60), nullable=True),
    sa.Column('grade_2', sa.String(length=60), nullable=True),
    sa.Column('grade_b', sa.String(length=60), nullable=True),
    sa.Column('grade_3', sa.String(length=60), nullable=True),
    sa.Column('grade_c', sa.String(length=60), nullable=True),
    sa.Column('grade_4', sa.String(length=60), nullable=True),
    sa.Column('grade_5', sa.String(length=60), nullable=True),
    sa.Column('grade_6', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_grade_1'), 'players', ['grade_1'], unique=False)
    op.create_index(op.f('ix_players_grade_2'), 'players', ['grade_2'], unique=False)
    op.create_index(op.f('ix_players_grade_3'), 'players', ['grade_3'], unique=False)
    op.create_index(op.f('ix_players_grade_4'), 'players', ['grade_4'], unique=False)
    op.create_index(op.f('ix_players_grade_5'), 'players', ['grade_5'], unique=False)
    op.create_index(op.f('ix_players_grade_6'), 'players', ['grade_6'], unique=False)
    op.create_index(op.f('ix_players_grade_a'), 'players', ['grade_a'], unique=False)
    op.create_index(op.f('ix_players_grade_b'), 'players', ['grade_b'], unique=False)
    op.create_index(op.f('ix_players_grade_c'), 'players', ['grade_c'], unique=False)
    op.create_index(op.f('ix_players_player_name'), 'players', ['player_name'], unique=False)
    op.create_index(op.f('ix_players_player_yob'), 'players', ['player_yob'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_player_yob'), table_name='players')
    op.drop_index(op.f('ix_players_player_name'), table_name='players')
    op.drop_index(op.f('ix_players_grade_c'), table_name='players')
    op.drop_index(op.f('ix_players_grade_b'), table_name='players')
    op.drop_index(op.f('ix_players_grade_a'), table_name='players')
    op.drop_index(op.f('ix_players_grade_6'), table_name='players')
    op.drop_index(op.f('ix_players_grade_5'), table_name='players')
    op.drop_index(op.f('ix_players_grade_4'), table_name='players')
    op.drop_index(op.f('ix_players_grade_3'), table_name='players')
    op.drop_index(op.f('ix_players_grade_2'), table_name='players')
    op.drop_index(op.f('ix_players_grade_1'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
