"""empty message

Revision ID: 889ae2d96f95
Revises: 3e192218884d
Create Date: 2017-04-21 03:45:12.873034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '889ae2d96f95'
down_revision = '3e192218884d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_players_player_name', table_name='players')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_players_player_name', 'players', ['player_name'], unique=False)
    # ### end Alembic commands ###
