"""empty message

Revision ID: b2776e5fb078
Revises: 889ae2d96f95
Create Date: 2017-04-21 04:00:20.730142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2776e5fb078'
down_revision = '889ae2d96f95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_players_player_name'), 'players', ['player_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_player_name'), table_name='players')
    # ### end Alembic commands ###
