"""empty message

Revision ID: b2aff92fc256
Revises: b2776e5fb078
Create Date: 2017-04-21 04:48:13.787734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2aff92fc256'
down_revision = 'b2776e5fb078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('player_id', sa.Integer(), nullable=False))
    op.drop_column('players', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('id', mysql.INTEGER(display_width=11), nullable=False))
    op.drop_column('players', 'player_id')
    # ### end Alembic commands ###
